language: python
python:
 - "2.7"

# install requirements
install:
 - sudo apt-get install postgresql-9.3 postgresql-client-9.3 libpq5
 - pip install -r requirements.txt

# Build with unit tests and coverage
script: 
 - python create_db.py
 - coverage run setup.py nosetests

# safelist
branches:
  only:
  - master # For all work approved for release
  - develop # For general development work

# Post-steps for successful builds
after_success:
 coveralls